[package]
name = "inference-server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
async-graphql = { version = "7" }
async-graphql-axum = "7"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tower-http = { version = "0.5", features = ["cors"] }
